### ISSUE TITLE
JToken.ToObject<T>() not working in expressions

### ISSUE THREAD

**Issue by goodrod** [dynamicexpresso/DynamicExpresso#327]
**Dynamic expression version**
<PackageReference Include="DynamicExpresso.Core" Version="2.16.1" />

**Problematic code**
```
        var interpreter = new Interpreter();
        var test = JObject.Parse("{ \"date\": \"2024-11-11T11:11:11Z\" }");
        interpreter.SetVariable("test", test);
        var result = interpreter.Eval("test.SelectToken(\"$.date\").ToObject<DateTime>()");
```

**Actual behavior**
The following exception:
```
DynamicExpresso.Exceptions.ParseException : '.' or '(' expected (at index 44).
   at DynamicExpresso.Parsing.Parser.ValidateToken(TokenId t, String errorMessage)
   at DynamicExpresso.Parsing.Parser.ParseTypeKeyword(Type type)
   at DynamicExpresso.Parsing.Parser.ParseIdentifier()
   at DynamicExpresso.Parsing.Parser.ParsePrimaryStart()
   at DynamicExpresso.Parsing.Parser.ParsePrimary()
   at DynamicExpresso.Parsing.Parser.ParseUnary()
   at DynamicExpresso.Parsing.Parser.ParseMultiplicative()
   at DynamicExpresso.Parsing.Parser.ParseAdditive()
   at DynamicExpresso.Parsing.Parser.ParseShift()
   at DynamicExpresso.Parsing.Parser.ParseComparison()
   at DynamicExpresso.Parsing.Parser.ParseLogicalAnd()
   at DynamicExpresso.Parsing.Parser.ParseLogicalXor()
   at DynamicExpresso.Parsing.Parser.ParseLogicalOr()
   at DynamicExpresso.Parsing.Parser.ParseConditionalAnd()
   at DynamicExpresso.Parsing.Parser.ParseConditionalOr()
   at DynamicExpresso.Parsing.Parser.ParseConditional()
   at DynamicExpresso.Parsing.Parser.ParseAssignment()
   at DynamicExpresso.Parsing.Parser.ParseExpressionSegment()
   at DynamicExpresso.Parsing.Parser.ParseExpressionSegment(Type returnType)
   at DynamicExpresso.Parsing.Parser.Parse()
   at DynamicExpresso.Parsing.Parser.Parse(ParserArguments arguments)
   at DynamicExpresso.Interpreter.ParseAsLambda(String expressionText, Type expressionType, Parameter[] parameters)
   at DynamicExpresso.Interpreter.Parse(String expressionText, Type expressionType, Parameter[] parameters)
   at DynamicExpresso.Interpreter.Eval(String expressionText, Type expressionType, Parameter[] parameters)
   at DynamicExpresso.Interpreter.Eval(String expressionText, Parameter[] parameters)
   at SatelliteCoreTest.ImportAttributeMappingHelperTest.microsoft_forms_should_work_with_empty_date() in /home/goodrod/work/projects/internal/Helios/HeliosCommon/SatelliteCoreTest/ImportAttributeMappingHelperTest.cs:line 265
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Expected behavior**
To return a DateTime parsed from the json.

**Comment by davideicardi** [comment]
Yes, unfortunately this is a know limitation, see https://github.com/dynamicexpresso/DynamicExpresso?tab=readme-ov-file#limitations
As usual any help is appreciated.
